[options]
CacheDir = /var/cache/pacman/pkg
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional TrustAll

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist
